### ISSUE TITLE
Fix TimeoutError during execution of build.py

### ISSUE THREAD

**Issue by kmrudin** [PyProveIt/Prove-It#8]
When build.py is called to do a clean build, it executes for several hours (which is to be expected), but crashes with a TimeoutError: Cell execution timed out.  Rerunning build.py picks up the build from where it left off, but eventually TimeoutError occurs again.  This has occurred multiple times, and efforts to complete the execution of build.py have been unsuccessful.  The roughly same* error message is provided each time, though it occurs while executing different Jupyter notebooks.   Also potentially relevant- the TimeoutError occurs during the handling of another exception.  

*The traceback below goes through line 519 in build (executeNotebook(proof_notebook)); a traceback going through line 557 (executeAndExportNotebook(expr_notebook)) has also been observed. 

Full traceback is as follows :

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 324, in _wait_for_reply
    msg = self.kc.shell_channel.get_msg(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 630, in <module>
    build(context_paths, all_paths, args.noexecute, args.just_execute_proofs, args.just_execute_demos, args.just_execute_expression_nbs)
  File "build.py", line 519, in build
    executeNotebook(proof_notebook)
  File "build.py", line 231, in executeNotebook
    executenb(nb, cwd=notebook_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 440, in executenb
    return ep.preprocess(nb, resources)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 262, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 280, in preprocess_cell
    reply, outputs = self.run_cell(cell, cell_index)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 348, in run_cell
    exec_reply = self._wait_for_reply(msg_id, cell)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 337, in _wait_for_reply
    raise exception("Cell execution timed out")
TimeoutError: Cell execution timed out

**Comment by wwitzel** [comment]
Should be fixed in the new "build" procedure that recycles the same jupyter kernel.  Kenny, see if you can do "python build.py --clean" then "python build.py" now.
